export const EXPENSE_LIST_REQUEST = 'EXPENSE_LIST_REQUEST'
export const EXPENSE_LIST_SUCCESS = 'EXPENSE_LIST_SUCCESS'
export const EXPENSE_LIST_FAIL = 'EXPENSE_LIST_FAIL'

export const EXPENSE_FILTER_REQUEST = 'EXPENSE_FILTER_REQUEST'
export const EXPENSE_FILTER_SUCCESS = 'EXPENSE_FILTER_SUCCESS'
export const EXPENSE_FILTER_FAIL = 'EXPENSE_FILTER_FAIL'

export const EXPENSE_REPORT_REQUEST = 'EXPENSE_REPORT_REQUEST'
export const EXPENSE_REPORT_SUCCESS = 'EXPENSE_REPORT_SUCCESS'
export const EXPENSE_REPORT_FAIL = 'EXPENSE_REPORT_FAIL'
